#!/usr/bin/python3
import os

d_dir='~/dmtcp'
su_dir=d_dir+'/static-util'
d_bin_dir=d_dir+'/bin'

glibc='glibc-2.26'
gbuild='glibc-build'

tmp_dir='/tmp/static_dmtcp_tmp'
cache_dir=tmp_dir+'/cache'
bad_cache_dir=tmp_dir+'/badcache'

print('Hello World;')

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Temporary Hack
if not os.path.exists(d_bin_dir+'/dmtcp_replace_symbols_elf'):
    os.system('make -C {0}'.format(su_dir))

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Makedir /dmtcp_tmp
try:
    os.mkdir(tmp_dir)
except OSError as e:
    pass
try:
    os.mkdir(cache_dir)
except OSError as e:
    pass

try:
    os.mkdir(bad_cache_dir)
except OSError as e:
    pass

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Build glibc with --enable-static-nss
if not os.path.exists(tmp_dir+'/'+glibc):
    os.system('cp {0}/{1}.tar.gz {2}; tar -xvzf {2}/{1}.tar.gz --one-top-level={2}'.format(su_dir, glibc, tmp_dir))


dir_to_check='{0}/{1}'.format(tmp_dir, gbuild) #/tmp/static_dmtcp_tmp/glibc-build
if not os.path.exists(dir_to_check):
    os.mkdir(dir_to_check)
    os.system('cd {2}; {0}/glibc-2.26/configure --prefix={2} --enable-static-nss; make -j'.format(tmp_dir, glibc, dir_to_check))

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Bring up libc.a + libpthread.a
os.system('cp {0}/glibc-build/libc.a {0}/glibc-build/nptl/libpthread.a {0}'.format(tmp_dir))

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Generate header and c files from symbols!

# 1) find the symbols from the source code of dmtcp
# *** *** dmtcp_wrapper_symbols has HARDCODED d_dir!!!
os.system('cd {0}; {1}/dmtcp_wrapper_symbols'.format(tmp_dir, d_bin_dir))

# 2) generate header and c files using dmtcp.wrapper.sym
if os.path.exists(tmp_dir+'/dmtcp.wrapper.sym'):
    # header and c files
    os.system('cd {0}; python3 {1}/dmtcp_static_gen -hfile dmtcp.wrapper.sym'.format(tmp_dir, d_bin_dir))
    os.system('cd {0}; python3 {1}/dmtcp_static_gen -cfile dmtcp.wrapper.sym'.format(tmp_dir, d_bin_dir))
    # generate the .o's for c file
    os.system('cd {0}; gcc -c -g -O0 dlsym_plt_DMTCP.c -o {1}/dlsym_plt_DMTCP.o'.format(tmp_dir, cache_dir))
else:
    perror("No dmtcp.wrapper.sym found")
    exit(1)

# 3) replace using the symbols for libc.a + libpthread.a
# BELOW

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Modify libc.a + libpthread.a

# libc.a
if os.path.exists(tmp_dir+'/libc.a'):
    # Extract
    os.system('cd {1}; ar -xvf {0}/libc.a'.format(tmp_dir, bad_cache_dir))
    # Modify + ar r
    os.system('cd {1}; {0}/dmtcp_replace_symbols_elf -o *.o -s `cat ../dmtcp.wrapper.sym` --singlestr=__dmtcp_plt --only_undef; ar r {2}/libc.a *.o'.format(d_bin_dir, bad_cache_dir, tmp_dir))
    # Copy over
    # Remove .o's
    os.system('cd {0}; rm -f *.o'.format(bad_cache_dir))
else:
    perror("No libc.a found")
    exit(1)

# libpthread.a
if os.path.exists(tmp_dir+'/libpthread.a'):
    # Extract
    os.system('cd {1}; ar -xvf {0}/libpthread.a'.format(tmp_dir, bad_cache_dir))
    # Modify + ar r
    os.system('cd {1}; {0}/dmtcp_replace_symbols_elf -o *.o -s `cat ../dmtcp.wrapper.sym` --singlestr=__dmtcp_plt --only_undef; ar r {2}/libpthread.a *.o'.format(d_bin_dir, bad_cache_dir, tmp_dir))
    # Remove .o's
    os.system('cd {0}; rm -f *.o'.format(bad_cache_dir))
else:
    perror("No libpthread.a found")
    exit(1)

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

exit(1)

# Bring in dmtcp.a
os.system('rm -f *.o *.a; cp '+d_dir+'/libs/*.a '+su_dir+';')
